-- MySQL Script generated by MySQL Workbench
-- Tue May 23 00:27:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema logistica_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `logistica_db` ;

-- -----------------------------------------------------
-- Schema logistica_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logistica_db` DEFAULT CHARACTER SET utf8 ;
USE `logistica_db` ;

-- -----------------------------------------------------
-- Table `logistica_db`.`lbd_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistica_db`.`lbd_clientes` (
  `cli_id` BIGINT(40) NOT NULL,
  `cli_nombre` VARCHAR(100) NOT NULL,
  `cli_num_identificacion` VARCHAR(45) NOT NULL,
  `cli_direccion` VARCHAR(200) NOT NULL,
  `cli_telefono` VARCHAR(30) NOT NULL,
  `cli_correo` VARCHAR(100) NULL,
  PRIMARY KEY (`cli_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistica_db`.`lbd_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistica_db`.`lbd_productos` (
  `pro_id` BIGINT(40) NOT NULL,
  `pro_nombre` VARCHAR(45) NOT NULL,
  `pro_precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistica_db`.`lbd_bodegas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistica_db`.`lbd_bodegas` (
  `bod_id` BIGINT(40) NOT NULL,
  `bod_nombre` VARCHAR(1) NOT NULL,
  `bod_direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`bod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistica_db`.`lbd_puertos_maritimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistica_db`.`lbd_puertos_maritimos` (
  `pm_id` BIGINT(40) NOT NULL,
  `pm_nombre` VARCHAR(45) NOT NULL,
  `pm_direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pm_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistica_db`.`lbd_logistica_maritima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistica_db`.`lbd_logistica_maritima` (
  `lm_id` BIGINT(40) NOT NULL,
  `lm_id_cliente` BIGINT(40) NOT NULL,
  `lm_id_producto` BIGINT(40) NOT NULL,
  `lm_cant_producto` INT NOT NULL,
  `lm_fecha_registro` DATE NOT NULL,
  `lm_fecha_entrega` DATE NOT NULL,
  `lm_id_puerto` BIGINT(40) NOT NULL,
  `lm_precio_normal` VARCHAR(45) NOT NULL,
  `lm_precio_descuento` VARCHAR(45) NULL,
  `lm_numero_flota` VARCHAR(45) NOT NULL,
  `lm_numero_guia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lm_id`),
  CONSTRAINT `id_log_mar_cliente`
    FOREIGN KEY (`lm_id_cliente`)
    REFERENCES `logistica_db`.`lbd_clientes` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_log_mar_producto`
    FOREIGN KEY (`lm_id_producto`)
    REFERENCES `logistica_db`.`lbd_productos` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_log_mar_puerto`
    FOREIGN KEY (`lm_id_puerto`)
    REFERENCES `logistica_db`.`lbd_puertos_maritimos` (`pm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_log_mar_cliente_idx` ON `logistica_db`.`lbd_logistica_maritima` (`lm_id_cliente` ASC);

CREATE INDEX `id_log_mar_producto_idx` ON `logistica_db`.`lbd_logistica_maritima` (`lm_id_producto` ASC);

CREATE INDEX `id_log_mar_puerto_idx` ON `logistica_db`.`lbd_logistica_maritima` (`lm_id_puerto` ASC);


-- -----------------------------------------------------
-- Table `logistica_db`.`lbd_logistica_terrestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistica_db`.`lbd_logistica_terrestre` (
  `lt_id` BIGINT(40) NOT NULL,
  `lt_id_cliente` BIGINT(40) NOT NULL,
  `lt_id_producto` BIGINT(40) NOT NULL,
  `lt_cant_producto` INT NOT NULL,
  `lt_fecha_registro` DATE NOT NULL,
  `lt_fecha_entrega` DATE NOT NULL,
  `lt_id_bodega` BIGINT(40) NOT NULL,
  `lt_precio_normal` VARCHAR(45) NOT NULL,
  `lt_precio_descuento` VARCHAR(45) NULL,
  `lt_placa_vehiculo` VARCHAR(45) NOT NULL,
  `lt_numero_guia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lt_id`),
  CONSTRAINT `id_log_ter_cliente`
    FOREIGN KEY (`lt_id_cliente`)
    REFERENCES `logistica_db`.`lbd_clientes` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_log_ter_producto`
    FOREIGN KEY (`lt_id_producto`)
    REFERENCES `logistica_db`.`lbd_productos` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_log_ter_bodega`
    FOREIGN KEY (`lt_id_bodega`)
    REFERENCES `logistica_db`.`lbd_bodegas` (`bod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_log_ter_cliente_idx` ON `logistica_db`.`lbd_logistica_terrestre` (`lt_id_cliente` ASC);

CREATE INDEX `id_log_ter_producto_idx` ON `logistica_db`.`lbd_logistica_terrestre` (`lt_id_producto` ASC);

CREATE INDEX `id_log_ter_bodega_idx` ON `logistica_db`.`lbd_logistica_terrestre` (`lt_id_bodega` ASC);


-- -----------------------------------------------------
-- Table `logistica_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistica_db`.`usuario` (
  `id` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(255) NULL,
  `created` DATE NULL,
  `isactive` BIT(1) NULL,
  `last_login` DATE NULL,
  `modified` DATE NULL,
  `nombre` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `role` VARCHAR(255) NULL,
  `token` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
